### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by thrust15** [BillyNate/home-assistant-component-spin-sdc-1#4]
Hi,

I'm trying out your component on 0.43.2 (python 3.4). 

I get the following error when starting up home assistant. I've followed your readme through. I did get it to work using your Python Quickstart code, I was able to see the actions I performed. 

Funny thing though, i'm able to change the led color, so there seems to be a connection. But i'm not able to register any events or get the correct profile in home assistant.

I'm running home assistant in a virtual environment. Please let me know how I can help.

```17-05-01 21:11:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 235, in _step
    result = coro.send(value)
  File "/home/homeassistant/.homeassistant/custom_components/spin_remote/spin_sdc_1.py", line 244, in async_on_time_interval
    yield from async_new_device_found(device)
  File "/home/homeassistant/.homeassistant/custom_components/spin_remote/spin_sdc_1.py", line 208, in async_new_device_found
    yield from async_add_devices([sdc1])```

**Comment by BillyNate** [comment]
Thanks for the feedback! 😃 
I'll look into it!

**Comment by thrust15** [comment]
I actually got it fixed :) When googling I stumbled on https://github.com/home-assistant/home-assistant/pull/6362/

So changing line 208 from
```python
yield from async_add_devices([sdc1])
``` 
to, removing 'yield from'
```python
async_add_devices([sdc1])
```
Fixed my issue and it worked like a charm (don't know why, but i'm glad it did :)).

**Comment by BillyNate** [comment]
Good to hear it worked!
It's the first feedback on this component, so I'm very happy to hear it works well on someone else's system too!
I'll apply the fix when I've found some spare time. Thank you for providing the URL! 😄
